version: '3.7'


networks:
  public: {}

services:
  go-service:
    image: go-service:latest
    container_name: go-service
    networks:
      - public
    ports:
      - "8081:80"

  dotnet-service:
    image: dotnet-service:latest
    container_name: dotnet-service
    networks:
      - public
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - public
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - public
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-data:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
